-- SELECT * FROM complaints;
-- SELECT * FROM customers;
-- SELECT * FROM deliverypartners;
-- SELECT * FROM deliveryupdates;
-- SELECT * FROM feedback;
-- SELECT * FROM menuitems;
-- SELECT * FROM orderdelivery;
-- SELECT * FROM orderitems;
-- SELECT * FROM orders;
-- SELECT * FROM payment;
-- SELECT * FROM restaurants;
------------------------------------------------------------------------------------
-- Q1. Display all customers who live in 'Delhi'.
-- SELECT 
--     *
-- FROM
--     customers
-- WHERE
--     city = 'Delhi';
---------------------------------------------------------------------------------------
-- Q2. Find the average rating of all restaurants in 'Mumbai'.
-- SELECT 
--     restaurant_id, name, city, AVG(rating)
-- FROM
--     restaurants
-- WHERE
--     city = 'Mumbai'
-- GROUP BY 1 , 2 , 3;

-- OR

-- SELECT 
--     AVG(rating) AS Average_Rating
-- FROM
--     restaurants
-- WHERE
--     city = 'Mumbai';
------------------------------------------------------------------------------
-- Q3. List all customers who have placed at least one order.
-- SELECT 
--     O.customer_id, C.name
-- FROM
--     orders AS O
--         INNER JOIN
--     customers AS C ON C.customer_id = O.customer_id
-- GROUP BY O.customer_id , C.name;
------------------------------------------------------------------------------------------
-- Q4. Display the total number of orders placed by each customer.
-- SELECT 
--     O.customer_id, C.name, COUNT(order_id) AS Count_Of_Orders
-- FROM
--     orders AS O
--         INNER JOIN
--     customers AS C ON C.customer_id = O.customer_id
-- GROUP BY O.customer_id , C.name;
----------------------------------------------------------------------------------
-- Q5. Find the total revenue generated by each restaurant.
-- SELECT 
--     R.restaurant_id, R.name, SUM(O.total_amount) AS Revenue
-- FROM
--     restaurants AS R
--         INNER JOIN
--     ORDERS AS O ON R.restaurant_id = O.restaurant_id
-- GROUP BY R.restaurant_id , R.name
-- ORDER BY Revenue DESC;
------------------------------------------------------------------------------
-- Q6. Find the top 5 restaurants with the highest average rating.
-- SELECT 
--     restaurant_id, name, city, AVG(rating) Avg_Rating
-- FROM
--     restaurants
-- GROUP BY 1 , 2 , 3
-- ORDER BY Avg_Rating DESC LIMIT 5;
-------------------------------------------------------------------------------------
-- Q7. Display all customers who have never placed an order.
-- SELECT 
--     C.customer_id, C.name
-- FROM
--     orders AS O
--         RIGHT JOIN
--     customers AS C ON C.customer_id = O.customer_id
-- WHERE
--     O.order_id IS NULL;
----------------------------------------------------------------------------------
-- Q8. Find the number of orders placed by each customer in 'Mumbai'.
-- SELECT 
--     C.customer_id,
--     C.name,
--     C.city,
--     COUNT(*) AS Total_Order_Placed
-- FROM
--     orders AS O
--         INNER JOIN
--     customers AS C ON C.customer_id = O.customer_id
-- WHERE
--     C.city = 'Mumbai'
-- GROUP BY C.customer_id , C.name , C.city;
------------------------------------------------------------------------------------------
-- Q9. Display all orders placed in the last 30 days.
-- SELECT 
--     *
-- FROM
--     orders
-- WHERE
--     order_date >= DATE_ADD((SELECT 
--                 MAX(order_date)
--             FROM
--                 orders),
--         INTERVAL - 30 DAY); 
-- OR
-- SELECT 
--     *
-- FROM
--     orders
-- WHERE
--     order_date >= DATE_ADD(CURDATE(), INTERVAL 30 DAY);
-------------------------------------------------------------------------------------
-- Q10. List all delivery partners who have completed more than 1 delivery.
-- SELECT 
--     DV.partner_id, DV.name, COUNT(*) AS Delivery_Count
-- FROM
--     orderdelivery AS OD
--         INNER JOIN
--     deliverypartners AS DV ON DV.partner_id = OD.partner_id
--         INNER JOIN
--     deliveryupdates AS DU ON DU.order_id = OD.order_id
-- WHERE
--     DU.status = 'Delivered'
-- GROUP BY DV.partner_id , DV.name
-- HAVING COUNT(*) > 1
-- ORDER BY Delivery_Count DESC;
-------------------------------------------------------------------------------------------------
-- Q11. Find the customers who have placed orders on exactly three different days.
-- SELECT C.customer_id, C.name, COUNT(DISTINCT O.order_date) AS Distinct_Order_Days
-- FROM orders AS O
-- INNER JOIN customers AS C ON C.customer_id = O.customer_id
-- GROUP BY C.customer_id, C.name
-- HAVING COUNT(DISTINCT O.order_date) =3;
------------------------------------------------------------------------------------------
-- Q12. Find the delivery partner who has worked with the most different customers.
-- SELECT 
--     DV.partner_id, DV.name, COUNT(DISTINCT O.customer_id) AS Unique_Customers
-- FROM
--     orderdelivery AS OD
--         INNER JOIN
--     deliverypartners AS DV ON DV.partner_id = OD.partner_id
--         INNER JOIN
--     orders AS O ON O.order_id = OD.order_id
-- GROUP BY DV.partner_id , DV.name
-- ORDER BY Unique_Customers DESC;
---------------------------------------------------------------------------------------------------------------------
-- Q13. Identify customers who have the same city and have placed orders at the same restaurants, but on different dates.
WITH OrderDetails AS (SELECT C.customer_id AS ID, C.name AS CustomerName, C.city AS City, R.name AS RestrauntName, R.restaurant_id, O.order_date
FROM orders AS O
JOIN customers AS C ON C.customer_id = O.customer_id
JOIN restaurants AS R ON R.restaurant_id = O.restaurant_id
)
SELECT O1.ID, O1.CustomerName, O1.City, O1.RestrauntName
FROM OrderDetails AS O1
JOIN OrderDetails AS O2 ON O1.City = O2.city AND O1.RestrauntName = O2.RestrauntName AND O1.order_date < O2.order_date AND O1.ID <> O2.ID;











